##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: test
  redis:
    host: redis.jxdinfo.com
    port: 6379
    password:
    jedis:
      pool:
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 3 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0      # 连接超时时间（毫秒）
  ###################  mongodb配置  ###################
  data:
    mongodb:
      host: mongodb.jxdinfo.com
      port: 27017
      database: log4j
  ###################  mysql配置  ###################
  #  datasource:
  #    url: jdbc:mysql://mysql.jxdinfo.com:3306/hussar?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  #    username: hussar
  #    password: hussar
  #    db-name: hussar
  #    filters: log4j,wall,mergeStat
  #    driverClassName: com.mysql.cj.jdbc.Driver
  ###################  oracle配置  ###################
  datasource:
    url: jdbc:oracle:thin:@oracle.jxdinfo.com:1521:orcl
    username: hussar_v8
    password: hussar_v8
    db-name: hussar_v8
    filters: log4j,wall,mergeStat
    driverClassName: oracle.jdbc.OracleDriver
    validation-query: select 1 from dual
###################  DM7配置  ###################
#  datasource:
#    driverClassName: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://dm.jxdinfo.com:5236
#    username: HUSSAR_V8
#    password: HUSSAR_V8
#    db-name: HUSSAR_V8